package main

import (
	"bytes"
	"context"
	"encoding/json"
	"log"
	"time"

	pb "github.com/fengbeihong/rpc-go/demo/pb"
	"google.golang.org/grpc"

	"github.com/grpc-ecosystem/grpc-gateway/runtime"

	"github.com/fengbeihong/rpc-go/rpc"
)

type echoServer struct {
}

func (s *echoServer) Echo(ctx context.Context, req *pb.StringMessage) (*pb.StringMessage, error) {
	return &pb.StringMessage{Value: req.GetValue()}, nil
}

/////////////////////////////
// 下面是自定义logger的例子，需要实现rpc.Logger接口，可以对接到不同服务使用的log库上
/////////////////////////////

type MyLogger struct {
}

func (m *MyLogger) Infof(format string, args ...interface{}) {
	log.Printf(format, args...)
}

func (m *MyLogger) Errorf(format string, args ...interface{}) {
	log.Printf(format, args...)
}

/////////////////////////////

func main() {
	s := rpc.InitRpc("./rpc.toml", rpc.WithLogger(&MyLogger{}))
	// 也可以使用默认logger
	// s := rpc.InitRpc("./rpc.toml")

	// register http with code generated by grpc-gateway
	{
		ctx := context.Background()
		ctx, cancel := context.WithCancel(ctx)
		defer cancel()

		mux := runtime.NewServeMux()
		err := pb.RegisterEchoServiceHandlerFromEndpoint(ctx, mux, s.GrpcServerEndpoint(), []grpc.DialOption{grpc.WithInsecure()})
		if err != nil {
			log.Printf("register http server failed, error: %s\n", err.Error())
		}
		s.ServeHttp(mux)
	}

	// register rpc
	pb.RegisterEchoServiceServer(s.GrpcServer(), &echoServer{})

	// 调用client的例子
	go clientExample()

	if err := s.Serve(); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}

func clientExample() {
	time.Sleep(time.Duration(2) * time.Second)
	clientExampleRpcConsul()
	clientExampleRpcLocal()
	clientExampleHttpLocal()
}

// 通过consul调用启动的rpc服务
func clientExampleRpcConsul() {
	conn, err := rpc.DialService(context.Background(), "rpcservername")
	if err != nil {
		log.Println("clientExampleRpcConsul error: ", err)
		return
	}
	defer conn.Close()
	c := pb.NewEchoServiceClient(conn)

	r, err := c.Echo(context.Background(), &pb.StringMessage{Value: "call rpc server with consul"})
	if err != nil {
		log.Println("clientExampleRpcConsul error: ", err)
		return
	}
	log.Println("clientExampleRpcConsul succeed, response: ", r.Value)
}

// 通过local配置调用启动的rpc服务
func clientExampleRpcLocal() {
	conn, err := rpc.DialService(context.Background(), "rpcservername_local")
	if err != nil {
		log.Println("clientExampleRpcLocal error: ", err)
		return
	}
	defer conn.Close()
	c := pb.NewEchoServiceClient(conn)

	r, err := c.Echo(context.Background(), &pb.StringMessage{Value: "call rpc server with local"})
	if err != nil {
		log.Println("clientExampleRpcLocal error: ", err)
		return
	}
	log.Println("clientExampleRpcLocal succeed, response: ", r.Value)
}

// 通过local配置调用http服务
func clientExampleHttpLocal() {
	data := map[string]interface{}{
		"value": "call http server with local",
	}
	bb, _ := json.Marshal(data)
	body := bytes.NewReader(bb)
	b, err := rpc.HttpPost(context.Background(), "rpcservername_http", "/v1/example/echo", body)
	if err != nil {
		log.Println("clientExampleHttpLocal error: ", err)
		return
	}
	log.Println("clientExampleHttpLocal succeed, response: ", string(b))
}
