env="dev"

#以下是默认的
[server]
#服务名称
service_name="rpcservername"
address = "0.0.0.0"
grpc_port = 9900
http_port = 9901

[pprof]
port=6060

[consul]
enabled=false
host="127.0.0.1"

[metrics]
enabled=true
type="prometheus"

[trace]
enabled=true
type="jaeger"
agent_port=6831

[[client]]
service_name="rpcservername"
proto="rpc"
type="consul"
endpoints="127.0.0.1:9900"
timeout=1000
retry_times = 3
per_retry_timeout=300

[[client]]
service_name="rpcservername_local"
proto="rpc"
type="local"
endpoints="127.0.0.1:9900"
timeout=1000
retry_times = 3
per_retry_timeout=300

[[client]]
service_name="rpcservername_http"
proto="http"
type="local"
endpoints="127.0.0.1:9901"
timeout=1000
retry_times = 3
per_retry_timeout=300

[[redis]]
service_name="redis_server_name"
address="127.0.0.1:19009"
password="password"
max_idle=20
idle_timeout=100
conn_timeout = 200
read_timeout=100
write_timeout=100

[[redis]]
service_name="redis_server_name2"
address="127.0.0.1:19010"
password="password"
max_idle=20
idle_timeout=100
conn_timeout = 200
read_timeout=100
write_timeout=100

[[database]]
service_name="mysql_service_name"
host="127.0.0.1"
port=3306
username="test"
password="pwdd"
database="testdatabase"
